server:
  assets-path: /app/assets

theme:
  background-color: 0 0 16
  primary-color: 43 59 81
  positive-color: 61 66 44
  negative-color: 6 96 59

pages:
  !include: pages.yml
  !include: home.yml
  !include: selfhost.yml
